### ISSUE TITLE
Automatically compile code

### ISSUE THREAD

**Issue by jdeast** [rpoleski/MulensModel#143] opened 2024-07-08 13:17 UTC
With conda?

**Comment by rpoleski** [comment] 2024-07-08 14:01
You mean to makefiles in `source/VBBL/` and `source/AdaptiveContouring`? I don't know what's the purpose of conda, but I'm not against it. Note - people mostly use PyPI and then these Makefiles are ignored.

**Comment by jdeast** [comment] 2024-07-08 14:23
My (limited) understanding is that pip can install code, but can't compile anything. Conda can do both, making the install easier. Conda is also required to install pymc (for that reason), so we're only simplifying the installation instructions.

**Comment by rpoleski** [comment] 2024-07-08 15:09
For clarity - currently we're importing C and C++ code using setuptools.Extension when MM is installed using PIP. @jdeast do you want to configure conda yourself?

**Comment by jdeast** [comment] 2024-07-08 15:12
I want it to work with 1 command, e.g.,

conda install exozippy

or 

conda install mulensmodel

I don't know how to do that (yet?), but I'm pretty sure it's possible, and I don't think it's possible with pip. I'm sure I can figure it out if you don't already know how do to that.

**Comment by rpoleski** [comment] 2024-07-08 21:00
```
pip install MulensModel
```
works. I don't know enough about conda to add this option.

**Comment by jdeast** [comment] 2024-07-08 22:12
But then I have to go to the vbbl directory and type make.

**Comment by rpoleski** [comment] 2024-07-09 05:25
No. 
There are 2 parallel wrappers for VBBL. One is using Extensions (and that one is used by PIP) and the other that compiles the code with appropriate flags (from Makefile; "installation" using PYTHONPATH).

**Comment by jdeast** [comment] 2024-07-09 09:04
I don't understand the difference. When I pip install and run it, I get
warnings related to not having run make in the vbbl directory.

**Comment by rpoleski** [comment] 2024-07-09 09:54
That means that somehow PIP didn't fully work. Can you uninstall MM, install it once more, and copy-paste full output here (or send me via email)?
It also means that the warning is not clear enough - we have not thought that pip install may fail.

**Comment by jdeast** [comment] 2024-07-09 10:11
Right, I wasn't using pip. I cloned the repo because we haven't pushed all
the updates to pypi which we needed.

However, when I install it via pip, I get an error about not having the
right shape, which I ran into before:

ValueError: could not broadcast input array from shape (38568,) into shape
 (38166,)

Of that error, Jennifer said: "You need to switch to mm v3. But maybe I
should try to fix it in master." We should probably update the version on
pypi too.

**Comment by rpoleski** [comment] 2024-07-09 16:32
Please post full error message.

**Comment by rpoleski** [comment] 2024-07-16 20:27
I've just installed MM by calling `pip install MulensModel` then I've run example 05. I got a bunch of warnings about calculating log10() of negative numbers (but these are caused by the data and model used). No error was reported. What's the problem? 
@jenniferyee can you comment on that?

**Comment by rpoleski** [comment] 2024-08-17 13:21
No reproducible error is presented, so I'm closing this thread.

**Closed by rpoleski** 2024-08-17 13:21 UTC
